---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s: "true"
spec:
  concurrency: 1
  version: v1.27.16+k3s1
  nodeSelector:
    matchExpressions:
      - key: k3s-upgrade
        operator: NotIn
        values:
          - disabled
          - "false"
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  serviceAccountName: system-upgrade
  drain:
    force: true
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s: "true"
spec:
  concurrency: 1
  version: v1.27.16+k3s1
  nodeSelector:
    matchExpressions:
      - key: k3s-upgrade
        operator: NotIn
        values:
          - disabled
          - "false"
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  drain:
    force: true
  upgrade:
    image: rancher/k3s-upgrade
