---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-upgrade
  namespace: system-upgrade
spec:
  concurrency: 1
  version: v1.27.16+k3s1
  nodeSelector:
    matchExpressions:
      - key: k3s-upgrade
        operator: NotIn
        values:
          - disabled
          - "false"
  serviceAccountName: system-upgrade
  drain:
    force: true
  upgrade:
    image: rancher/k3s-upgrade
