---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flatcar-linux-update-operator
  namespace: argocd
spec:
  project: default
  source:
    path: flatcar-linux-update-operator/overlays/default
    repoURL: https://github.com/adborden/k8s-lab.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: reboot-coordinator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
