---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gateway
  namespace: argocd
spec:
  project: default
  source:
    path: k8s-gateway
    repoURL: https://github.com/adborden/k8s-lab.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
