---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  project: default
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: v1.17.6
    helm:
      valuesObject:
        ingress:
          dashboard:
            host:
              name: ceph.fl.a14n.net
            ingressClassName: nginx
            tls:
              - hosts:
                  - ceph.fl.a14n.net
                secretName: rook-ceph-cluster-tls
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
        monitoring:
          enabled: true
          createPrometheusRules: true
        toolbox:
          enabled: true
        cephClusterSpec:
          dashboard:
            enabled: true
            ssl: false
          placement:
            all:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: a14n.net/storage
                          operator: In
                          values:
                            - ceph
          removeOSDsIfOutAndSafeToRemove: true
        cephBlockPools:
          - name: ceph-blockpool-ssd
            spec:
              failureDomain: host
              replicated:
                size: 3
              deviceClass: ssd
            storageClass:
              enabled: true
              name: ceph-ssd
              isDefault: true
              volumeBindingMode: WaitForFirstConsumer
              parameters:
                imageFormat: "2"
                imageFeatures: layering

                csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
                csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
                csi.storage.k8s.io/fstype: ext4
          - name: ceph-blockpool-hdd
            spec:
              failureDomain: host
              replicated:
                size: 3
              deviceClass: hdd
            storageClass:
              enabled: true
              name: ceph-hdd
              isDefault: false
              volumeBindingMode: WaitForFirstConsumer
              parameters:
                imageFormat: "2"
                imageFeatures: layering

                csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
                csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
                csi.storage.k8s.io/fstype: ext4
        cephBlockPoolsVolumeSnapshotClass:
          enabled: true
          isDefault: true

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
