---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  project: default
  source:
    path: system-upgrade-controller/overlays/fl.a14n.net
    repoURL: https://github.com/adborden/k8s-lab.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: reboot-coordinator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
