---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca
  namespace: vault
spec:
  isCA: true
  commonName: vault-ca
  secretName: vault-ca-keypair
  duration: 8760h  # 1 year
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca
  namespace: vault
spec:
  ca:
    secretName: vault-ca-keypair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server
spec:
  commonName: vault.vault.svc
  dnsNames:
    - vault.vault.svc
    - vault.vault.svc.cluster.local
  secretName: vault-server-tls
  issuerRef:
    name: vault-ca
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-client
spec:
  commonName: vault.vault.svc
  secretName: vault-client-tls
  usages:
    - client auth
  issuerRef:
    name: vault-ca
    kind: Issuer
