---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - resources/plan-k3s-upgrade.yaml

patches:
  - target:
      group: upgrade.cattle.io
      kind: Plan
      labelSelector: k3s=true
    patch: |-
      - op: replace
        path: /spec/channel
        value: https://update.k3s.io/v1-release/channels/stable
