---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - resources/plan-k3s-upgrade.yaml

patches:
  - target:
      group: upgrade.cattle.io
      kind: Plan
      labelSelector: k3s=true
    patch: |-
      - op: replace
        path: /spec/version
        value: v1.29.9+k3s1
