---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/flatcar/flatcar-linux-update-operator.git//examples/deploy?ref=v0.9.0

patches:
  - path: patches/daemonset.yaml
