---
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: a14n-velero-backups
      config:
        s3Url: https://s3.us-west-002.backblazeb2.com
        region: us-west-002
        checksumAlgorithm: ""
      credential:
        name: velero-b2
        key: aws
  volumeSnapshotLocation:
    - name: default
      provider: csi
      credential: {}
      config: {}
  features: EnableCSI
