---
env:
  TZ: America/Los_Angeles

image:
  # renovate: datasource=docker depName=ghcr.io/dgtlmoon/changedetection.io
  tag: 0.50.38

ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: changedetection.fl.a14n.net
        paths:
          - path: /
    tls:
      - hosts:
          - changedetection.fl.a14n.net
        secretName: changedetection-tls

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
