---
name: lint
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - uses: Gr1N/setup-poetry@v9
      - name: install python dependencies
        run: poetry install --with=dev
      - name: install ansible dependencies
        run: make setup
      - name: lint
        run: make lint
